#!/bin/sh

cur=`pwd`


go build -buildmode=plugin -o libso.so libso/main.go 
go build -buildmode=plugin -o TestModule.so module/main.go 
go build -o loader libso_load/main.go 

go build -race -o df dataflow/main.go 

cd ${cur}
